name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy black typing-extensions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 src/pyprojroot2 tests
      - name: MyPy (type) checking
        run: |
          mypy --strict src/pyprojroot2
      - name: Format with black
        run: |
          black --check --diff src/pyprojroot2 tests
      - name: Test with pytest
        run: |
          PYTHONPATH=src pytest